import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import LoginAuthBtn from './LoginAuthBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}

const Navbar = () => {
    return (
        <div className="navbar">
            <Link href="/" className="logo">
                Appleforum
            </Link>
            <Link href="/list">List</Link>
            <Link href="/write">Write</Link>
            <LoginAuthBtn />
        </div>
    );
};
