import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import LoginAuthBtn from './LoginAuthBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { Session } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let 로그인정보 = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                    <LoginAuthBtn 로그인정보={로그인정보} />
                </div>
                {children}
            </body>
        </html>
    );
}
